import {
	uniArrowRight,
	uniAngleRightB,
	uniCheck,
	uniCheckCircle,
	uniCheckThinline,
	uniCheckSquare,
	uniEnvelope,
	uniLayerGroupMonochrome,
	uniPhone,
	uniShoppingCart,
	uniSignout,
	uniSquare,
	uniUser,
	uniYoutube,
} from 'vue-unicons/dist/icons'

export default [
	uniArrowRight,
	uniAngleRightB,
	uniCheck,
	uniCheckCircle,
	uniCheckThinline,
	uniCheckSquare,
	uniEnvelope,
	uniLayerGroupMonochrome,
	uniPhone,
	uniShoppingCart,
	uniSignout,
	uniSquare,
	uniUser,
	uniYoutube,
]