import {
	uniArrowRight,
	uniAngleDown,
	uniAngleRight,
	uniAngleLeft,
	uniAngleRightB,
	uniCheck,
	uniCheckCircle,
	uniCheckThinline,
	uniCheckSquare,
	uniCopy,
	uniEnvelope,
	uniFile,
	uniLayerGroupMonochrome,
	uniPhone,
	uniPlay,
	uniShoppingCart,
	uniSignout,
	uniSquare,
	uniTimes,
	uniUser,
	uniYoutube,
} from 'vue-unicons/dist/icons'

export default [
	uniArrowRight,
	uniAngleDown,
	uniAngleRight,
	uniAngleLeft,
	uniAngleRightB,
	uniCheck,
	uniCheckCircle,
	uniCheckThinline,
	uniCheckSquare,
	uniCopy,
	uniEnvelope,
	uniFile,
	uniLayerGroupMonochrome,
	uniPhone,
	uniPlay,
	uniShoppingCart,
	uniSignout,
	uniSquare,
	uniTimes,
	uniUser,
	uniYoutube,
]